INSERT INTO tb_movie(title, year, poster) VALUES ('It', 2017,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('(500) Days of Summer', 2009,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f9mbM0YMLpYemcWx6o2WeiYQLDP.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('The Breakfast Club', 1985,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vSqk5BeQ1HvP9wq0rWZyWqiwXeF.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Life Is Beautiful', 1997,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('The Florida Project', 2017,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bnSTP1PY2fDyat0eUa4QouuGV7F.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Deadpool', 2016,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Guardians of the Galaxy', 2014,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Guardians of the Galaxy Vol. 2', 2017,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Avengers: Infinity War', 2018,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg')
INSERT INTO tb_movie(title, year, poster) VALUES ('Avengers: Endgame', 2019,'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/or06FN3Dka5tukK1e9sl16pB3iy.jpg')